New "Colors" page
tradingview/pine_script_docs pull request #162
Opened 2021-05-31 00:26 UTC by LucFF

2021-05-31 18:27 UTC, vgladkov requested changes
approve fixes pls

2021-05-31 18:27 UTC, vgladkov commented on source/essential/Colors.rst
> +To undertand how this code works, one must first know that `pivothigh() <https://www.tradingview.com/pine-script-reference/v4/#fun_pivothigh>`__ and `pivotlow() <https://www.tradingview.com/pine-scri
> used as they are here without an argument to the ``source`` parameter

But they have `source` in the code above

2021-05-31 18:27 UTC, vgladkov commented on source/essential/Colors.rst
> +In this example we take our CCI indicator in another direction. We will build dynamically adjusting extremes zone buffers using a Donchian Channel (historical highs/lows) calculated from the CCI. We
```suggestion
In this example we take our CCI indicator in another direction. We will build dynamically adjusting extremes zone buffers using a Donchian Channel (historical highs/lows) calculated from the CCI. We build the top/bottom bands by making them 1/4 the height of the DC. We will use a dynamically adjusting lookback to calculate the DC. To modulate the lookback, we will calculate a simple measure of volatility by keeping a ratio of a short-period ATR to a long one. When that ratio is higher than 50 of its last 100 values, we consider the volatility high. When the volatility is high/low, we decrease/increase the lookback.
```

2021-05-31 18:27 UTC, vgladkov commented on source/essential/Colors.rst
> +Providing a selection of color presets in your inputs—rather than a single color that can be changed—can help color-challenged users. Our `Technical Ratings <https://www.tradingview.com/script/Jdw7wW
```suggestion
Providing a selection of color presets in your inputs — rather than a single color that can be changed — can help color-challenged users. Our `Technical Ratings <https://www.tradingview.com/script/Jdw7wW2g-Technical-Ratings/>`__ demonstrates one way of achieving this. The `Pine Color Magic and Chart Theme Simulator <https://www.tradingview.com/script/yyDYIrRQ-Pine-Color-Magic-and-Chart-Theme-Simulator/>`__ script provides a good selection of base colors to build from.
```

2021-05-31 18:32 UTC, LucFF commented on source/essential/Colors.rst
> +To undertand how this code works, one must first know that `pivothigh() <https://www.tradingview.com/pine-script-reference/v4/#fun_pivothigh>`__ and `pivotlow() <https://www.tradingview.com/pine-scri
Oops! Sry.

2021-06-01 10:12 UTC, vgladkov approved these changes

2021-06-01 10:16 UTC, vgladkov requested changes

2021-06-01 10:16 UTC, vgladkov commented on source/essential/Colors.rst
> +    pLo := nz(pivotlow( low,  i_legs, i_legs), pLo)
```suggestion
    pHi := nz(pivothigh(i_legs, i_legs), pHi)
    pLo := nz(pivotlow( i_legs, i_legs), pLo)
```

2021-06-01 15:42 UTC, vgladkov approved these changes

2021-06-01 15:44 UTC, merged